### ISSUE TITLE
TeraStation WSH5610

### ISSUE THREAD

**Issue by LETRA** [1000001101000/Debian_on_Intel_Terastations#1]
Hi. I do not see the TeraStation WSH5610 https://www.buffalo-technology.com/productpage/terastation-wsh5610dns2/ device in the list. Do you think it will work or should I make some special adjustment?

**Comment by 1000001101000** [comment]
Good to hear from you!

The installer should work just fine, I expect most of my customization will work too but won't know for sure until we try. If there's anything specific to this device that needs tweaking I should be able to add some logic to the installer to handle it provided we can 

I don't have one of these devices and Buffalo doesn't appear to have posted any new source code for this series (presumably since they don't offer a Linux version). Assuming this model is at least somewhat similar to previous models we should be able to account for any differences if you're willing to perform a few tests once you get Debian running.

You'll know right away if the microcontroller interface is working because it will display "Debian Installer" on the LCD screen if it's working correctly. 

Let me know when you get a chance to give it a try!

**Comment by 1000001101000** [comment]
also, I'm currently working through a final issue with the new "Buster" installer. If you'd rather move forward with Buster rather than Stretch that will be available soon.

**Comment by LETRA** [comment]
Thank you very much for your help!

I'm about to receive the device. I bought it on ebay at a great bargain. I can wait for Buster's installer. When I receive the device I want to increase to 8GB of RAM and look for a new SSD m2 to save the Buffalo m2 installation for security. Then I will test the installation of Debian with your scripts and you may be able to test me to ensure that this device is compatible.

My idea is to use this Buffalo Terastation as a roon server https://roonlabs.com It is a bit short processor (minimum requirements are i3, although many people say comfortable with Celeron) and I think Debian can help me improve the perfomance of the system more than Windows Server 2012.

I will follow the project and install debian when you have everything ready. Many thanks.

**Comment by 1000001101000** [comment]
awesome. sounds like a fun project!

I found upgrading the Memory in the other Intel Devices relatively straight forward (I've done it for the TS5800 and the TS-8VHL). The DDR3 ram for the TS5800 was really cheap too, I imagine 8GB will be more expensive but still sounds like a good plan.

If you're planning to upgrade the memory, would you be willing to take some pictures of the device (inside and out)?

I'd like to create a wiki page for this device similar to what I've made for the TS5800:
https://buffalonas.miraheze.org/wiki/Terastation_TS5800DN

**Comment by LETRA** [comment]
Yes, I will document the modifications and send you the photographs. For example, I read that Buffalo does not help users with any recommendation about upgrades. And that they are business customers. They do not say that the 6x2TB model can be extended, to 4TB, 8TB or maybe, although I will not try it, 10TB. They do not offer other S.O. And Windows Server 2012 ends its support in 2022. There are still stores that offer this device for more than € 3000 with 6x2TB configurations. I bought it without records, and it seems completely new, but it has not yet arrived from Germany. I want to play with this and leave the information available when the support for many users ends.

Among the data that I have to get is exactly which RAM models are compatible with Celeron j1900 and which SSD m2. I hope to get more specific data when that arrives and safely perform these modifications.

**Comment by 1000001101000** [comment]
sounds like we have similar goals.

I assume Windows Server 2008 EOL is why many of the older models have ended up on ebay, Hopefully that means I'll be able to pick up one of these newer devices on the cheap in the next few years. You can often find threads about what drive configurations work with which older devices on Buffalo's forum but they don't seem interested in maintaining that type of information.

I assume we won't have to do anything special to boot from the SSD m2 (I'm a little surprised to hear that this device uses them). If Buffalo is using it to boot into windows the motherboard must support booting from them. For my home PC I use one on a motherboard that won't boot from them, it's fairly simple to still use for your rootfs and just install the bootloader on another drive. Hopefully that won't be necessary.

**Comment by LETRA** [comment]
I have not dived in the forums of Buffalo but I found before yesterday a thread looking for upgrades and there were previous models that used the first hdd for system and firmware updates and bios. I still do not know what autonomy this model is going to leave me with. But my idea is not to use the m2 that comes with the device and save it as backup of the s.o. original, at least for the moment. Buy a new m2 and install there Debian. Then try to see what RAID configuration I do (I want to raid 10 and I would like to delay it a bit more so that the disks come down in price).

If I'm not wrong, the m2 of the WSH5610 may be what you see on the right:

![wsh5610dns2-02-768x640](https://user-images.githubusercontent.com/16805254/60371812-acb61a80-99fa-11e9-97bf-a5e2247d5bd8.png)

**Comment by 1000001101000** [comment]
I like that idea, it might be an opportunity to get a larger/faster model though I imagine the speed will mostly be limited to the pcie speed available on the motherboard. I think the one I have can go >1.5x as fast as my current motherboard can handle. it's still a lot faster than the equivalent sata drive. 

If you find that that m2 is an odd shape or otherwise is hard to replace you could also take an image of it and keep that safe. You could do this by booting into the debian installer and dumping the image before running the install.

**Comment by 1000001101000** [comment]
I see you just noticed what I just noticed about that picture :p

**Comment by 1000001101000** [comment]
I've published the Buster image. Buster is planned to become the new Debian "Stable" release next week. I'd recommend going to Buster unless you need some piece of software that isn't ready for it. 

I took a peek at the roon page, I don't think they've updated their compatibility info in may years but I'm sure there's info out there somewhere.

**Comment by LETRA** [comment]
Currently the price of the m2 is so good that I do not consider running the risk of making a system backup in a usb. I also want to use the ws2012 a bit to compare the performance of Roon with Debian. Currently I have installed Roon in a mini mac 2012 2012 and I have tested in a Qnap of two bays without internal ssd with a result a little low. Roon demands a lot of resources to handle a large volume of metadata, rather than folders with music albums. I know that Debian can be good at this if I choose the file system of the base system and optimize it, but I will make the choice based on the results of Roon. At that time I want to have both m2 ready and opt for one or the other based on how good it is going to be for this project.

The photo I edited immediately after posting the post. At first I thought the m2 was accessible and had been placed there to make life more comfortable. Then I saw that it was the security lock of the door. The design of Buffalo is not distinguished by that kind of sophisticated and user friendly solutions ^

![wsh5610dns2-02-768x640](https://user-images.githubusercontent.com/16805254/60374178-64e7c100-9a03-11e9-9248-d7671b5061f7.png)

**Comment by LETRA** [comment]
They constantly update compatible devices. the requirements have not changed and insist that for libraries of more than 12,000 albums an i7 is necessary. However there are users who are comfortable on a NAS with Celeron. I installed it also on a Qnap TS-253A and the boot of the app took more than five minutes with 20,000 high-res albums. Then the response speed was almost as good as that of the mac mini i7. In Roon they develop server and client applications for windows, mac and linux. And they have their own Linux distribution (ROCK) optimized for the Roon core that runs on Intel NUC. The problem with this distribution is that it can not be modified. I can not add a torrent or soulseek client or a backup security service in the cloud like Backblaze or Jottacloud.

https://kb.roonlabs.com/Roon_Optimized_Core_Kit

**Comment by 1000001101000** [comment]
Sounds like you’ve done your research. I’m looking forward to seeing how this works out.

**Comment by LETRA** [comment]
Let's wait for it to arrive and see how it works. And in any case you will have documented this generation of Terastation with the photos, the installation and the data that you need.

**Comment by LETRA** [comment]
Hello! I have received it and it is indeed completely new. I had to remove the plastic, open the bags and even open the microSD card where there is a copy to restore the WS2012 system. Everything is perfect but I can not connect to the terastation. I get the "Z" and "L" errors that I have consulted and they occur when the RAID is incomplete. I have only installed one disk to test the system but it does not give me access. And I still do not have six disks available to mount the RAID. I think it's time to try Debian and try a JBOD there. You can help? Your installation instructions do not know if they are applicable to this model and I do not know where to start ^

**Comment by 1000001101000** [comment]
Looks like this is slightly different for this model than for the older models:

The first step is to download one of the installer images from the repository and write it to a usb drive (dd if=ts-buster-installer.iso of=/dev/sdX bs=512). Then you need to tell the terastation to boot from it rather than the hard drives. If all the drives are blank it may try this on it's own but more likely you need to tell it to do so. On the older devices there was a switch on the back to tell it to boot form "HDD" or "USB". For this model it looks like you'll need to connect a keyboard and monitor to the device and select the usb device form the boot menu (or possibly change the boot order within the BIOS).

The user manual describes this process when using Buffalo's recovery disk:
http://manual.buffalo.jp/buf-doc/35021116-04_EN.pdf

The process listed in the user manual for this device is basically:
Connect a keyboard and the usb drive to the TeraStation using a USB 3.0 or 2.0 port.
Connect the monitor to the TeraStation using a HDMI or VGA port.
Press the power button to turn the TeraStation on.
Press the F11 key some times until the "Please select boot device:" is displayed. When it's displayed, stop
pressing F11. If it not displayed, repeat from the step 1.
Press the Down Arrow key and select the usb drive, then press the Enter key.

**Comment by LETRA** [comment]
Yesterday night I started to struggle with the installation and, as always, there are small mistakes with Debian that remind me of the worst moments when this distribution was ten years ago. First of all your scripts are not installed. I have tried the normal and advanced installation, with ssh and without ssh and there is no trace. I also have a lot of error messages in the boot. And Debian does not love my language. I know that everything can be fixed, but it is a lot of hours in something with a lot of summer heat in Spain...

I don't want to use Windows (I've been too Linux for thirteen years before moving to Mac) so I've already announced the Terastation in a Telegram group in Spanish.

Tell me what information you want from the device  and what you would like it to photograph before selling it.

[The message of the first photo comes out at the beginning of the installation. The second message is repeated for two minutes in the boot]

![IMG_0324](https://user-images.githubusercontent.com/16805254/60548079-87d6e580-9d21-11e9-8830-8f13d72bd286.jpg)
![IMG_0325](https://user-images.githubusercontent.com/16805254/60548081-87d6e580-9d21-11e9-90c8-684fb31790f5.jpg)

**Comment by 1000001101000** [comment]
I'll adjust the installer so that it can continue if the lcd initialization fails. It must work differently for that model in some way that causes a failure. a better testing strategy would have been to start with the normal debian installer and then test my customizations post-install (possibly on a different distro if you prefer). 

For pictures I hoped for pictures of the board close enough read the markings on some of the chips (ethernet controller etc). If you aren't planning to upgrade the ram any longer that may be too inconvenient. Some pictures of the outside would still be nice (I don't use the ones provided by Buffalo for copyright reasons).

**Comment by 1000001101000** [comment]
I’ve posted the updated installer images.

**Comment by LETRA** [comment]
Yesterday I tried with the new Buster installers and your scripts are still not installed. The only possibility I see is that Debian gives the option to write in the EFI boot. And I've always rejected that possibility in case there was a failure and I no longer had the option to restore the WS2012 installation.

System Down continues to appear on the screen and the same boot start error occurs in that it does not recognize the bays. Neither the system mounts the disks (in my case two bays with 4TB disks and four are without disks).

The "failed to run preseeded command" fault in the Debian installation no longer occurs.

I have also tried the Roon server, which was my project for this machine, and it is slow for this purpose, the Celeron processor is not recommended for Roon. As I bought it cheap I will sell it since it is completely new, in its box and with all the accessories.

You can use all these photos and if you want any more, tell me before I sell it.

![IMG_0353](https://user-images.githubusercontent.com/16805254/60989051-46f45780-a345-11e9-9538-029543f2524b.jpg)
![IMG_0354](https://user-images.githubusercontent.com/16805254/60989052-46f45780-a345-11e9-8b24-bb180376aa61.jpg)
![IMG_0355](https://user-images.githubusercontent.com/16805254/60989053-46f45780-a345-11e9-8ecd-825aa90a7015.jpg)
![IMG_0356](https://user-images.githubusercontent.com/16805254/60989054-46f45780-a345-11e9-8d74-95ad98d4d0d0.jpg)
![IMG_0357](https://user-images.githubusercontent.com/16805254/60989055-46f45780-a345-11e9-8b96-19ef9323c34f.jpg)
![IMG_0358](https://user-images.githubusercontent.com/16805254/60989056-478cee00-a345-11e9-8a6a-1a63824725d2.jpg)

**Comment by 1000001101000** [comment]
Does that mean you were never able to get a Debian install to boot?

My main curiosity at this point would be whether we can interface with the on-board microcontroller or not. The preseed failure you saw in the installer tells us it doesn't work as-is, this might just be because the serial port it uses isn't /dev/ttyS1 like the other devices. You could verify this by:

1. Boot into a Debian LiveCD image such as: https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.0.0-amd64-xfce.iso
2. Set up the needed python libraries
    apt-get install python3 python3-pip git
    pip3-install pyserial
3. Download the microcontroller library
    git clone https://github.com/1000001101000/Python_buffalo_libmicon
4. Run "micon_dump.py" to attempt to read values form the microcontroller
    cd Python_buffalo_libmicon
    ./micon_dump.py
5. If it returns errors try changing the serial port in micon_dump.py from /dev/ttyS1 to /dev/tty[023] and try again until it succeeds or until you confirm none of them work.

If it does work with a different port I'll update the installer so that future users might have more luck

**Comment by LETRA** [comment]
Yes, on all occasions I was able to complete the Debian installation. This time I also installed the Roon server and I was testing it with an external 10TB disk.

I'm going to try all this tonight or tomorrow. Yesterday I had a good temperature here and I was comfortable with all the devices and screens on.

Soon I will give you more news.

**Comment by 1000001101000** [comment]
That's good to hear. If you are booting into an image created by my installer I'd also be interested to see the output of:
lsmod
ls /sys/class/gpio
sensors

Thanks again!

**Comment by 1000001101000** [comment]
any luck?

**Comment by LETRA** [comment]
Sorry for the long delay.

```
letra@debian:~$ lsmod
Module                  Size  Used by
intel_rapl             24576  0
intel_soc_dts_thermal    16384  0
intel_soc_dts_iosf     16384  1 intel_soc_dts_thermal
intel_powerclamp       16384  0
coretemp               16384  0
kvm_intel             245760  0
kvm                   724992  1 kvm_intel
irqbypass              16384  1 kvm
crct10dif_pclmul       16384  0
crc32_pclmul           16384  0
snd_hda_codec_hdmi     57344  1
snd_hda_intel          45056  2
ghash_clmulni_intel    16384  0
sg                     36864  0
snd_hda_codec         151552  2 snd_hda_codec_hdmi,snd_hda_intel
intel_cstate           16384  0
serio_raw              16384  0
snd_hda_core           94208  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
pcspkr                 16384  0
snd_hwdep              16384  1 snd_hda_codec
snd_pcm               114688  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
snd_timer              36864  1 snd_pcm
iTCO_wdt               16384  0
snd                    94208  10 snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_timer,snd_pcm
iTCO_vendor_support    16384  1 iTCO_wdt
soundcore              16384  1 snd
dw_dmac                16384  0
dw_dmac_core           28672  1 dw_dmac
evdev                  28672  12
pwm_lpss_platform      16384  0
pcc_cpufreq            16384  0
pwm_lpss               16384  1 pwm_lpss_platform
gpio_ich               16384  0
hwmon_vid              16384  0
parport_pc             32768  0
ppdev                  20480  0
lp                     20480  0
parport                57344  3 parport_pc,lp,ppdev
ip_tables              28672  0
x_tables               45056  1 ip_tables
autofs4                49152  2
ext4                  733184  1
crc16                  16384  1 ext4
mbcache                16384  1 ext4
jbd2                  122880  1 ext4
crc32c_generic         16384  0
fscrypto               32768  1 ext4
ecb                    16384  0
crypto_simd            16384  0
cryptd                 28672  2 crypto_simd,ghash_clmulni_intel
glue_helper            16384  0
aes_x86_64             20480  0
hid_generic            16384  0
usbhid                 57344  0
sd_mod                 61440  3
i915                 1728512  4
xhci_pci               16384  0
xhci_hcd              266240  1 xhci_pci
crc32c_intel           24576  2
psmouse               172032  0
usbcore               290816  3 xhci_hcd,usbhid,xhci_pci
igb                   245760  0
ahci                   40960  2
drm_kms_helper        200704  1 i915
libahci                40960  1 ahci
libata                270336  2 libahci,ahci
i2c_i801               28672  0
lpc_ich                28672  0
drm                   483328  5 drm_kms_helper,i915
scsi_mod              245760  3 sd_mod,libata,sg
dca                    16384  1 igb
i2c_algo_bit           16384  2 igb,i915
usb_common             16384  1 usbcore
thermal                20480  0
fan                    16384  0
i2c_hid                24576  0
video                  45056  1 i915
hid                   135168  3 i2c_hid,usbhid,hid_generic
button                 16384  0
```
```
letra@debian:~$ ls /sys/class/gpio
export  gpiochip338  gpiochip382  gpiochip410  unexport
```
```
letra@debian:~$ sensors
soc_dts0-virtual-0
Adapter: Virtual device
temp1:        +45.0°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +26.8°C  (crit = +90.0°C)

soc_dts1-virtual-0
Adapter: Virtual device
temp1:        +48.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +45.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:       +45.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:       +47.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:       +47.0°C  (high = +105.0°C, crit = +105.0°C)
```

Ask me all the information you need. I have time now.

**Comment by 1000001101000** [comment]
Excellent!

From your output I can see that this device does not use the it87 chip like the previous models did which is good to know. 

From what I was able to see in the windows firmware files this generation uses an on-board microcontroller like the older devices, attempting to get that working is the main thing I would like to accomplish. Please try the following:

1. Set up the needed python libraries
apt-get install python3 python3-pip git
pip3-install pyserial
2. Download the microcontroller library
git clone https://github.com/1000001101000/Python_buffalo_libmicon
3. Run "micon_dump.py" to attempt to read values form the microcontroller
cd Python_buffalo_libmicon
./micon_dump.py
4. If it returns errors try changing the serial port in micon_dump.py from /dev/ttyS1 to /dev/tty[023] and try again until it succeeds or until you confirm none of them work.

another thing you can do is run "sensors-detect" and see if it discovers any sensors to monitor the fans or not. The previous generations all did but it might all be via the microcontroller like on the arm models

after that the only thing left would be to try probing the gpio chips (which were detected successfully) and try to determine if they control any buttons/leds/hotswap bays like the other models. I can provide some scripts that make that easier..

**Comment by LETRA** [comment]
Same error in desktop term and TTY1:

```
letra@debian:~/Python_buffalo_libmicon$ ./micon_dump.py
Traceback (most recent call last):
  File "/home/letra/.local/lib/python3.7/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyS1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./micon_dump.py", line 5, in <module>
    test = libmicon.micon_api("/dev/ttyS1")
  File "/home/letra/Python_buffalo_libmicon/libmicon.py", line 179, in __init__
    self.port = serial.Serial(serial_port, 38400, serial.EIGHTBITS, serial.PARITY_EVEN, stopbits=serial.STOPBITS_ONE, timeout=0.25)
  File "/home/letra/.local/lib/python3.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/letra/.local/lib/python3.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyS1: [Errno 13] Permission denied: '/dev/ttyS1'
letra@debian:~/Python_buffalo_libmicon$ 
```

**Comment by 1000001101000** [comment]
could you try again with ttyS0/ttyS1 but running as root?

**Comment by 1000001101000** [comment]
also could you confirm which ports currently exist:
ls /dev | grep ttyS

**Comment by LETRA** [comment]
```
letra@debian:~/Python_buffalo_libmicon$ sudo ./micon_dump.py
Traceback (most recent call last):
  File "./micon_dump.py", line 3, in <module>
    import libmicon
  File "/home/letra/Python_buffalo_libmicon/libmicon.py", line 5, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
```

**Comment by LETRA** [comment]
```
letra@debian:~/Python_buffalo_libmicon$ ls /dev | grep ttyS
ttyS0
ttyS1
ttyS2
ttyS3
```

**Comment by 1000001101000** [comment]
try sudo su to get a root shell then re-run "pip3 install pyserial" then you should be able to try with all 4 of those.

**Comment by 1000001101000** [comment]
on the ts3000 series the microcontroller was on ttyS3. If it ends up being the same on this one I can re-use the same code I'm using in the arm version of the installer to make this one work.

**Comment by LETRA** [comment]
Only sudo in this installation, I think. I configure with ubuntu style without 

```
admin.letra@debian:~/Python_buffalo_libmicon$ sudo su-
sudo: su-: command not found
letra@debian:~/Python_buffalo_libmicon$ su -
Contraseña: 
su: Fallo de autenticación
```

**Comment by LETRA** [comment]
> on the ts3000 series the microcontroller was on ttyS3. If it ends up being the same on this one I can re-use the same code I'm using in the arm version of the installer to make this one work.

Same error in ttyS3:
```

letra@debian:~/Python_buffalo_libmicon$ ./micon_dump.py
Traceback (most recent call last):
  File "/home/letra/.local/lib/python3.7/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyS3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./micon_dump.py", line 5, in <module>
    test = libmicon.micon_api("/dev/ttyS3")
  File "/home/letra/Python_buffalo_libmicon/libmicon.py", line 179, in __init__
    self.port = serial.Serial(serial_port, 38400, serial.EIGHTBITS, serial.PARITY_EVEN, stopbits=serial.STOPBITS_ONE, timeout=0.25)
  File "/home/letra/.local/lib/python3.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/letra/.local/lib/python3.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyS3: [Errno 13] Permission denied: '/dev/ttyS3'

With sudo:

```
letra@debian:~/Python_buffalo_libmicon$ sudo ./micon_dump.py
Traceback (most recent call last):
  File "./micon_dump.py", line 3, in <module>
    import libmicon
  File "/home/letra/Python_buffalo_libmicon/libmicon.py", line 5, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

```



```

**Comment by 1000001101000** [comment]
here's a page that describes why this is happening with your setup:
https://stackoverflow.com/questions/7969540/pythonpath-not-working-for-sudo-on-gnu-linux-works-for-root

here is a recommended workaround:
`sudo -HE env PATH=$PATH PYTHONPATH=$PYTHONPATH ./bin/myscript`

**Comment by LETRA** [comment]
What script?

**Comment by 1000001101000** [comment]
sorry,
./micon_dump.py

**Comment by 1000001101000** [comment]
sudo -HE env PATH=$PATH PYTHONPATH=$PYTHONPATH ./micon_dump.py

**Comment by LETRA** [comment]
```
letra@debian:~/Python_buffalo_libmicon$ sudo sudo -HE env PATH=$PATH PYTHONPATH=$PYTHONPATH ./micon_dump.py
Traceback (most recent call last):
  File "./micon_dump.py", line 3, in <module>
    import libmicon
  File "/home/letra/Python_buffalo_libmicon/libmicon.py", line 5, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
letra@debian:~/Python_buffalo_libmicon$ 
```

**Comment by LETRA** [comment]
Would you like to access my machine via ssh and do the tests?

**Comment by 1000001101000** [comment]
that would be great

**Comment by LETRA** [comment]
Perfect. How can I give you the access data in private?

**Comment by 1000001101000** [comment]
email me at jeremy@jeremypeper.com

i'll be taking my email out of the comment shortly, let me know when you get it

**Comment by 1000001101000** [comment]
I got your message

**Comment by 1000001101000** [comment]
I spent some time trying to make the microcontroller script work and looking at the other things that I mentioned. I learned a lot about the hardware setup of the device but didn't get the microcontroller interface working. I took another look at the windows drivers and can see that there are multiple dlls for connecting to the different model series, this one must work differently than the older generations.

I can see that the windows utility has strings indicating it controls fans/buttons and drive bays similar to the older models, either it controls these directly via GPIO or it might use a different type of microcontroller interface.

**Comment by LETRA** [comment]
So this model is not compatible with Debian or do you need more time?

**Comment by 1000001101000** [comment]
It's compatible with Debian you just don't have control of the leds/fans/lcd etc. I used my ts5800 like that for almost a year before I figured out how to control the microcontroller interface and it worked fine.

With enough time and some hands on work we should be able to figure out how to get everything working but it's up to you if you're interested in that. Anything that's directly connected to a GPIO pin will be pretty easy to figure out. For inputs you basically push buttons and add/remove drives and take note of which GPIO pins values change which allows us to map them. For outputs we'd loop through them turning them on and off and note which ones cause leds to turn on/etc. If they're not using a microcontoller for this model we should even see the lcd react to come of the pins which could narrow down how it's connected. 

I suppose if you pointed a webcam at the front I could work through the process looking for leds but most of the process needs to be done by someone close enough to push buttons etc.

**Comment by LETRA** [comment]
I don't know how long it would take you to do it and I would like to sell it. I will sell it for only a part of its price but I suppose if you were interested it would be a big problem to send it to the United States.

**Comment by 1000001101000** [comment]
If you're planing to sell it it's probably not worth the effort at this time, there's a lot of trial and error involved in mapping the GPIO pins and trying to reverse engineer a different microcontroller connection without any GPL source as a starting point would be difficult and time consuming. 

You've given me a good starting point for when/if I get my hands on one of these sometime in the future.

**Comment by LETRA** [comment]
It's a shame. I have put it on sale on ebay for double the price at which I have offered it. I would have liked the machine to stay someone who writes an open source script and helps people for free. If you think about it, as long as the machine goes on sale, I keep that price to you. And the hundred shipping are indicative, you can find the cheapest transport and it is discounted.

**Comment by 1000001101000** [comment]
@LETRA I assume you sold your device a long time ago but if not, we've made some progress with a WS5220 which I think may work mostly the same as your device. If you do still have it let me know, I'll have some things for you to test in a few days.

**Comment by LETRA** [comment]
Thank you for remembering. I sold it very quickly. But it's great that you're still working on these machines that can still have a second long life with Linux.
