### ISSUE TITLE
Software RAID 1 - Grub cannot install to the MBR of either drive

### ISSUE THREAD

**Issue by windswept321** [1000001101000/Debian_on_Intel_Terastations#4]
I am trying to install this with the current bootable usb ISO on a dual drive Windows / Atom terastation (WS5200DWR2). 
the installer fails at the bootloader install part, as do repeated attempts or go-overs. 

Does anyone have any advice?

**Comment by windswept321** [comment]
<img width="914" alt="Screenshot 2020-12-29 at 02 37 16" src="https://user-images.githubusercontent.com/10297044/103255906-0a764a80-4983-11eb-8e92-e1e483fdc06f.png">
<img width="914" alt="Screenshot 2020-12-29 at 02 39 11" src="https://user-images.githubusercontent.com/10297044/103255908-0cd8a480-4983-11eb-8de4-267d4e4e0f7f.png">

**Comment by 1000001101000** [comment]
Good to hear from you!

I’m guessing you need to add a “BIOS boot partition” for grub to install for your configuration. It allows grub to install additional code needs for raid/etc that don't fit in the mbr.

I .... don’t see that I’ve documented that anywhere which seems like an oversight.  I’m guessing the Linux-based Buffalo firmware must come with these partitions which is probably why most people haven’t run into it before now.

I believe you can create one from the partitioning menu but haven’t looked at it in a while. I can boot up the installer on a device when I’m online tomorrow and take a look if needed.


In the meantime here is what my partition table looks like for my ts5000:
```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048           18431   8.0 MiB     EF02  BIOS boot partition
   2           18432        20989951   10.0 GiB    8300  Linux filesystem
   3        20989952        29378559   4.0 GiB     8300  Linux filesystem
   4        29378560      7814037134   3.6 TiB     8300  Linux filesystem

```

**Comment by 1000001101000** [comment]
I just ran through an install with the following drive layout which worked without issues:

![Screenshot_2020-12-29_11-43-07](https://user-images.githubusercontent.com/38921757/103304322-f6a40600-49cd-11eb-9a58-b260bbf27e1a.png)

**Comment by windswept321** [comment]
I have it working now, thanks!
